# log/error file at ~/.cache/starship/session_${xxx}.log
# config doc at https://starship.rs/config/

format = """ \
$shell\
$username\
$sudo\
$time\
$directory\
$git_branch\
$git_commit\
$git_metrics\
$c\
$cmake\
$python\
$golang\
$lua\
$rust\
$package
$character"""

add_newline = true
command_timeout = 1500

[username]
style_user = 'green'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

[shell]
disabled = false
fish_indicator = "󰈺"
bash_indicator = ""
zsh_indicator = ""
powershell_indicator = ""
nu_indicator = "NuShell"
unknown_indicator = "󰟢"
format = "[$indicator](cyan) "

[sudo]
disabled = false

[time]
disabled = false
style = 'green'

[directory]
truncation_length = 5
home_symbol = ""

[git_metrics]
disabled = false
added_style = 'bold blue'
deleted_style = 'bold red'
format = '[+$added]($added_style) / [-$deleted]($deleted_style) '

[c]
symbol = "󰙱 "
detect_extensions = ['cc', 'cpp', 'c', 'hpp', 'h']

[python]
symbol = '󰌠 '
pyenv_version_name = true

[golang]
symbol = "󰟓 "

[lua]
symbol = "󰢱 "

[rust]
symbol = "󱘗 "

[package]
disabled = false

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ➜](bold red) '